filebeat.inputs:
    - type: log
      enabled: true
      paths:
          - "/usr/share/filebeat/app-logging/*.log"
      tail_files: true

output.logstash:
    hosts: "logstash:5000"

multiline.pattern: "^[[:space:]]"
multiline.negate: false
multiline.match: after
